version: '3.7'

services:
  app:
    build: .
    volumes:
      - D:/projects/resume/sushi/sushi-frontend/:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: ['npm', 'run', 'serve']
    environment:
      - CHOKIDAR_USEPOLLING=true